### ISSUE TITLE
Download links are broken

### ISSUE THREAD

**Issue by mefjuu** [jackaudio/jackaudio.github.com#65] opened 2017-03-19 01:54 UTC
Links to Windows binaries are broken: http://jackaudio.github.io/downloads/

**Comment by lasconic** [comment] 2017-03-20 09:57
Not sure who is in charge of the website, but you could maybe request some free storage to OSUOSL and store the binaries there.

**Comment by mseeber** [comment] 2017-03-20 10:06
This is a known problem.
The releases are managed by @sletz, who is also in charge of providing the binaries, so I think he is going to decide where to host the binaries.

**Comment by brownerthanu** [comment] 2017-03-21 18:14
This is causing a problem with a time-sensitive project I'm working on. Would really appreciate if this would be fixed quickly.

**Comment by michaelmaw** [comment] 2017-03-28 03:14
Is there any way to download the Windows binaries from another link? I wanted to try out Jack with Musescore, but no downloads available...

**Comment by mseeber** [comment] 2017-03-28 14:43
Apparently you could use the version included with Radium:
https://github.com/jackaudio/jack2/issues/258#issuecomment-289663637

**Comment by ssfrr** [comment] 2017-03-29 16:23
also now downloadable from github: https://github.com/jackaudio/jackaudio.github.com/releases

**Comment by michaelmaw** [comment] 2017-03-29 19:25
Great! That link works.

**Comment by lordcheeto** [comment] 2017-04-08 19:25
It would be best if the releases were in their respective repos (e.g. https://github.com/jackaudio/jack2/releases), since this makes it impossible to tell which commits the releases were based on.

**Comment by lordcheeto** [comment] 2017-04-08 19:29
The source downloads are also for this repo, since they are built off tags in this repo.

**Comment by mseeber** [comment] 2017-04-16 15:46
This is a known issue, I will see if I can convince people to attach the binaries to the jack2 repo.

**Comment by falkTX** [comment] 2017-08-08 20:59
afaik the download links work now. please confirm so we can close this issue.
(the binaries are in the wrong place I guess, but that's a minor thing. will be solved with new releases anyway)

good news though - I have access to jackaudio.org now, so I can update the website when needed.
ping me on irc and I'll update it quickly.

**Comment by michaelmaw** [comment] 2017-08-09 04:13
Confirmed. Links work now. Thanks!

**Comment by falkTX** [comment] 2017-08-09 07:34
Alright, thanks for confirming. I'm closing the bug then.

**Closed by falkTX** 2017-08-09 07:34 UTC
